include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/**.freezed.dart"
    - "**/**.assets.gen.dart"

  errors:
    invalid_annotation_target: ignore
    unnecessary_string_escapes: ignore
    unused_import: error
