name: smart_learning_assistant
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Riverpod and hooks_riverpod for state management
  flutter_riverpod: ^3.0.0-dev.16
  hooks_riverpod: ^3.0.0-dev.16
  flutter_hooks:
  riverpod_annotation: ^3.0.0-dev.16

  # Router for navigation
  go_router: ^16.0.0

  # Call API for making HTTP requests
  dio: ^5.8.0+1
  path: ^1.8.3
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # Logger
  logger: ^2.6.1

  path_provider: ^2.1.5
  image_picker: ^1.1.2

  #Sql lite for local database
  sqflite: ^2.4.2
  flutter_math_fork: ^0.7.4

  # Theme
  material_color_utilities: ^0.11.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Build runner and generators for code generation
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  freezed: ^3.1.0
  retrofit_generator:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-100.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-200.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-300.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-400.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-500.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-600.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-800.otf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
